import React from "react";
import Tile from "../components/primitives/elements/Tile";
import Wall from "../components/primitives/elements/Wall";
import Ceiling from "../components/primitives/elements/Ceiling";
import Plank from "../components/primitives/elements/Plank";
import Stair from "../components/primitives/elements/Stair";
import Handrail from "../components/primitives/elements/Handrail";
import Door from "../components/Door";

// Import dungeon elements
import {
  Torch,
  Barrel,
  Chest,
  SpikeTrap,
  Pillar,
  Chain,
  Brazier,
  Spikes,
  Web,
  MetalGate,
  GlassWall,
} from "../components/primitives/elements";

// Import material elements
import {
  CrackedBrick,
  Stone,
  WoodPlank,
  MetalBar,
  Glass,
} from "../components/primitives/elements";

// Import complex primitives
import {
  Brick,
  ConcreteSlab,
  StoneWall,
  WoodenFence,
  WoodenBridge,
  DungeonCell,
  DungeonAltar,
  DungeonThrone,
  DungeonGate,
} from "../components/primitives/elements";

export interface RoomConfig {
  type: string;
  component: React.ComponentType<any>;
  title: string;
  emoji: string;
  description: string;
  props?: any;
  availableActions?: any[];
  editableProps?: any[];
  category: "rooms" | "biome" | "object" | "element";
  subcategory?: string;
}

const ELEMENT_CONFIGS: RoomConfig[] = [
  {
    type: "tile",
    component: Tile,
    title: "Tile",
    emoji: "🔲",
    description: "Basic floor tile",
    props: {
      position: [0, 0, 0],
      size: 1,
      color: "#8B4513",
    },
    category: "element",
    editableProps: [
      {
        key: "size",
        label: "Size",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "wall",
    component: Wall,
    title: "Wall",
    emoji: "🧱",
    description: "Basic wall segment",
    props: {
      position: [0, 0, 0],
      width: 2,
      height: 3,
      depth: 0.2,
      color: "#696969",
      material: "brick",
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 0.01,
        max: 2,
        step: 0.01,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "material",
        label: "Material",
        type: "select",
        options: [
          { value: "stone", label: "Stone" },
          { value: "brick", label: "Brick" },
          { value: "wood", label: "Wood" },
          { value: "plaster", label: "Plaster" },
          { value: "metal", label: "Metal" },
          { value: "concrete", label: "Concrete" },
        ],
      },
    ],
  },
  {
    type: "ceiling",
    component: Ceiling,
    title: "Ceiling",
    emoji: "🏠",
    description: "Basic ceiling tile",
    props: {
      position: [0, 0, 0],
      size: 2,
      color: "#D2B48C",
    },
    category: "element",
    editableProps: [
      {
        key: "size",
        label: "Size",
        type: "number",
        min: 0.1,
        max: 10,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "plank",
    component: Plank,
    title: "Plank",
    emoji: "🪵",
    description: "Wooden plank",
    props: {
      position: [0, 0, 0],
      length: 2,
      color: "#8B4513",
    },
    category: "element",
    editableProps: [
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "stair",
    component: Stair,
    title: "Stair",
    emoji: "🪜",
    description: "Staircase segment",
    props: {
      position: [0, 0, 0],
      width: 1,
      height: 1,
      depth: 1,
      color: "#8B4513",
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "handrail",
    component: Handrail,
    title: "Handrail",
    emoji: "🪝",
    description: "Safety handrail",
    props: {
      position: [0, 0, 0],
      length: 2,
      height: 1,
      color: "#C0C0C0",
    },
    category: "element",
    editableProps: [
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 0.1,
        max: 3,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  // Dungeon Elements
  {
    type: "torch",
    component: Torch,
    title: "Torch",
    emoji: "🔥",
    description: "Flickering torch with light",
    props: {
      position: [0, 0, 0],
      color: "#ff6b35",
      intensity: 2,
      flicker: true,
      scale: 1,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "intensity",
        label: "Light Intensity",
        type: "number",
        min: 0.5,
        max: 5,
        step: 0.1,
      },
      {
        key: "flicker",
        label: "Flicker",
        type: "boolean",
      },
    ],
  },
  {
    type: "barrel",
    component: Barrel,
    title: "Barrel",
    emoji: "🛢️",
    description: "Wooden barrel container",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      health: 3,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "health",
        label: "Health",
        type: "number",
        min: 1,
        max: 10,
        step: 1,
      },
    ],
  },
  {
    type: "chest",
    component: Chest,
    title: "Treasure Chest",
    emoji: "📦",
    description: "Interactive treasure chest",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      isOpen: false,
      treasure: "Gold",
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "treasure",
        label: "Treasure Type",
        type: "text",
      },
    ],
  },
  {
    type: "door",
    component: Door,
    title: "Door",
    emoji: "🚪",
    description: "Interactive door with lock",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      isOpen: false,
      isLocked: false,
      keyRequired: "iron_key",
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "isLocked",
        label: "Locked",
        type: "boolean",
      },
      {
        key: "keyRequired",
        label: "Key Required",
        type: "text",
      },
    ],
  },
  {
    type: "spike-trap",
    component: SpikeTrap,
    title: "Spike Trap",
    emoji: "⚡",
    description: "Dangerous spike trap",
    props: {
      position: [0, 0, 0],
      color: "#C0C0C0",
      scale: 1,
      isActive: true,
      damage: 10,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "isActive",
        label: "Active",
        type: "boolean",
      },
      {
        key: "damage",
        label: "Damage",
        type: "number",
        min: 1,
        max: 50,
        step: 1,
      },
    ],
  },
  // Additional Dungeon Elements
  {
    type: "pillar",
    component: Pillar,
    title: "Pillar",
    emoji: "🏛️",
    description: "Decorative stone pillar",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      height: 3,
      radius: 0.3,
      hasCap: true,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 10,
        step: 0.1,
      },
      {
        key: "radius",
        label: "Radius",
        type: "number",
        min: 0.1,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    type: "chain",
    component: Chain,
    title: "Chain",
    emoji: "⛓️",
    description: "Swinging metal chain",
    props: {
      position: [0, 0, 0],
      color: "#C0C0C0",
      scale: 1,
      length: 3,
      links: 8,
      swing: true,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 1,
        max: 10,
        step: 0.1,
      },
      {
        key: "swing",
        label: "Swing",
        type: "boolean",
      },
    ],
  },
  {
    type: "brazier",
    component: Brazier,
    title: "Brazier",
    emoji: "🔥",
    description: "Large fire brazier with light",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      isLit: true,
      flameColor: "#ff6b35",
      intensity: 2,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "isLit",
        label: "Lit",
        type: "boolean",
      },
      {
        key: "flameColor",
        label: "Flame Color",
        type: "color",
      },
    ],
  },
  {
    type: "spikes",
    component: Spikes,
    title: "Spikes",
    emoji: "⚡",
    description: "Dangerous spike field",
    props: {
      position: [0, 0, 0],
      color: "#C0C0C0",
      scale: 1,
      count: 9,
      height: 0.5,
      damage: 15,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "count",
        label: "Spike Count",
        type: "number",
        min: 1,
        max: 25,
        step: 1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 0.1,
        max: 2,
        step: 0.1,
      },
    ],
  },
  {
    type: "web",
    component: Web,
    title: "Spider Web",
    emoji: "🕸️",
    description: "Sticky spider web",
    props: {
      position: [0, 0, 0],
      color: "#F5F5DC",
      scale: 1,
      size: 2,
      sticky: true,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "size",
        label: "Size",
        type: "number",
        min: 0.5,
        max: 5,
        step: 0.1,
      },
      {
        key: "sticky",
        label: "Sticky",
        type: "boolean",
      },
    ],
  },
  // Building Block Primitives
  {
    type: "brick",
    component: Brick,
    title: "Brick",
    emoji: "🧱",
    description: "Building brick block",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      brickType: "standard",
      size: [1, 0.5, 0.5],
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "brickType",
        label: "Brick Type",
        type: "select",
        options: [
          { value: "standard", label: "Standard" },
          { value: "weathered", label: "Weathered" },
          { value: "ancient", label: "Ancient" },
          { value: "modern", label: "Modern" },
        ],
      },
    ],
  },
  {
    type: "cracked-brick",
    component: CrackedBrick,
    title: "Cracked Brick",
    emoji: "🧱💥",
    description: "Cracked brick with different damage levels",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      crackIntensity: "medium",
      size: [1, 0.5, 0.5],
      enabled: true,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "crackIntensity",
        label: "Crack Intensity",
        type: "select",
        options: [
          { value: "light", label: "Light" },
          { value: "medium", label: "Medium" },
          { value: "heavy", label: "Heavy" },
        ],
      },
      {
        key: "enabled",
        label: "Breaking Enabled",
        type: "boolean",
      },
    ],
  },
  {
    type: "stone",
    component: Stone,
    title: "Stone",
    emoji: "🪨",
    description: "Stone building block",
    props: {
      position: [0, 0, 0],
      color: "#696969",
      scale: 1,
      stoneType: "cobblestone",
      size: [1, 0.8, 1],
      shape: "cube",
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "stoneType",
        label: "Stone Type",
        type: "select",
        options: [
          { value: "cobblestone", label: "Cobblestone" },
          { value: "marble", label: "Marble" },
          { value: "granite", label: "Granite" },
          { value: "limestone", label: "Limestone" },
          { value: "sandstone", label: "Sandstone" },
        ],
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: [
          { value: "cube", label: "Cube" },
          { value: "irregular", label: "Irregular" },
          { value: "rounded", label: "Rounded" },
        ],
      },
    ],
  },
  {
    type: "wood-plank",
    component: WoodPlank,
    title: "Wood Plank",
    emoji: "🪵",
    description: "Wooden plank board",
    props: {
      position: [0, 0, 0],
      color: "#8B4513",
      scale: 1,
      woodType: "oak",
      size: [2, 0.2, 0.5],
      grainDirection: "horizontal",
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "woodType",
        label: "Wood Type",
        type: "select",
        options: [
          { value: "oak", label: "Oak" },
          { value: "pine", label: "Pine" },
          { value: "mahogany", label: "Mahogany" },
          { value: "cedar", label: "Cedar" },
          { value: "birch", label: "Birch" },
        ],
      },
      {
        key: "grainDirection",
        label: "Grain Direction",
        type: "select",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "vertical", label: "Vertical" },
        ],
      },
    ],
  },
  {
    type: "metal-bar",
    component: MetalBar,
    title: "Metal Bar",
    emoji: "🔩",
    description: "Metal bar or rod",
    props: {
      position: [0, 0, 0],
      color: "#C0C0C0",
      scale: 1,
      metalType: "iron",
      size: [2, 0.1, 0.1],
      shape: "round",
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "metalType",
        label: "Metal Type",
        type: "select",
        options: [
          { value: "iron", label: "Iron" },
          { value: "steel", label: "Steel" },
          { value: "copper", label: "Copper" },
          { value: "bronze", label: "Bronze" },
          { value: "gold", label: "Gold" },
        ],
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: [
          { value: "round", label: "Round" },
          { value: "square", label: "Square" },
          { value: "hexagonal", label: "Hexagonal" },
        ],
      },
    ],
  },
  {
    type: "glass",
    component: Glass,
    title: "Glass",
    emoji: "🪟",
    description: "Glass panel or window",
    props: {
      position: [0, 0, 0],
      color: "#E6F3FF",
      scale: 1,
      glassType: "clear",
      size: [1, 1, 0.1],
      thickness: 0.1,
    },
    category: "element",
    editableProps: [
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "glassType",
        label: "Glass Type",
        type: "select",
        options: [
          { value: "clear", label: "Clear" },
          { value: "tinted", label: "Tinted" },
          { value: "frosted", label: "Frosted" },
          { value: "stained", label: "Stained" },
          { value: "safety", label: "Safety" },
        ],
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "number",
        min: 0.01,
        max: 0.5,
        step: 0.01,
      },
    ],
  },
  // Complex primitives made from smaller building blocks
  {
    type: "stone-wall",
    component: StoneWall,
    title: "Stone Wall",
    emoji: "🏛️",
    description: "Wall made from individual stone blocks",
    props: {
      position: [0, 0, 0],
      width: 8,
      height: 4,
      depth: 0.5,
      color: "#8B7355",
      hasWindows: false,
      windowCount: 1,
      hasDoors: false,
      doorWidth: 2,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 20,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 10,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 0.1,
        max: 2,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasWindows",
        label: "Has Windows",
        type: "checkbox",
      },
      {
        key: "windowCount",
        label: "Window Count",
        type: "number",
        min: 0,
        max: 5,
        step: 1,
      },
      {
        key: "hasDoors",
        label: "Has Doors",
        type: "checkbox",
      },
      {
        key: "doorWidth",
        label: "Door Width",
        type: "number",
        min: 1,
        max: 4,
        step: 0.5,
      },
    ],
  },
  {
    type: "wooden-fence",
    component: WoodenFence,
    title: "Wooden Fence",
    emoji: "🚧",
    description: "Fence made from wooden planks and posts",
    props: {
      position: [0, 0, 0],
      length: 8,
      height: 2,
      color: "#8B4513",
    },
    category: "element",
    editableProps: [
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 2,
        max: 20,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 5,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "concrete-slab",
    component: ConcreteSlab,
    title: "Concrete Slab",
    emoji: "🏗️",
    description: "Slab made from concrete blocks",
    props: {
      position: [0, 0, 0],
      width: 6,
      length: 8,
      thickness: 0.3,
      color: "#C0C0C0",
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 20,
        step: 0.5,
      },
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 2,
        max: 20,
        step: 0.5,
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "number",
        min: 0.1,
        max: 2,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "metal-gate",
    component: MetalGate,
    title: "Metal Gate",
    emoji: "🚪",
    description: "Gate made from metal bars",
    props: {
      position: [0, 0, 0],
      width: 4,
      height: 3,
      color: "#C0C0C0",
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 10,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 8,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
    ],
  },
  {
    type: "glass-wall",
    component: GlassWall,
    title: "Glass Wall",
    emoji: "🪟",
    description: "Wall made from glass panels",
    props: {
      position: [0, 0, 0],
      width: 6,
      height: 3,
      depth: 0.1,
      color: "#E6F3FF",
      opacity: 0.3,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 15,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 8,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 0.05,
        max: 0.5,
        step: 0.05,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "opacity",
        label: "Opacity",
        type: "number",
        min: 0.1,
        max: 1,
        step: 0.1,
      },
    ],
  },
  // Additional complex primitives made from smaller building blocks
  {
    type: "wooden-bridge",
    component: WoodenBridge,
    title: "Wooden Bridge",
    emoji: "🌉",
    description: "Bridge made from wooden planks and posts",
    props: {
      position: [0, 0, 0],
      length: 12,
      width: 3,
      height: 2,
      color: "#8B4513",
      hasRails: true,
      hasSupportPillars: true,
    },
    category: "element",
    editableProps: [
      {
        key: "length",
        label: "Length",
        type: "number",
        min: 6,
        max: 30,
        step: 0.5,
      },
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 8,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 6,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasRails",
        label: "Has Rails",
        type: "checkbox",
      },
      {
        key: "hasSupportPillars",
        label: "Has Support Pillars",
        type: "checkbox",
      },
    ],
  },
  // Dungeon-themed complex primitives
  {
    type: "dungeon-cell",
    component: DungeonCell,
    title: "Dungeon Cell",
    emoji: "🔒",
    description: "Prison cell with bars, chains, and straw",
    props: {
      position: [0, 0, 0],
      width: 4,
      height: 3,
      depth: 4,
      color: "#8B7355",
      hasBars: true,
      barCount: 6,
      hasDoor: true,
      doorWidth: 1.5,
      hasChains: true,
      chainCount: 2,
      hasStraw: true,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 3,
        max: 8,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 2,
        max: 6,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 3,
        max: 8,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasBars",
        label: "Has Bars",
        type: "checkbox",
      },
      {
        key: "barCount",
        label: "Bar Count",
        type: "number",
        min: 4,
        max: 12,
        step: 1,
      },
      {
        key: "hasDoor",
        label: "Has Door",
        type: "checkbox",
      },
      {
        key: "doorWidth",
        label: "Door Width",
        type: "number",
        min: 1,
        max: 3,
        step: 0.5,
      },
      {
        key: "hasChains",
        label: "Has Chains",
        type: "checkbox",
      },
      {
        key: "chainCount",
        label: "Chain Count",
        type: "number",
        min: 1,
        max: 6,
        step: 1,
      },
      {
        key: "hasStraw",
        label: "Has Straw",
        type: "checkbox",
      },
    ],
  },
  {
    type: "dungeon-altar",
    component: DungeonAltar,
    title: "Dungeon Altar",
    emoji: "⚰️",
    description: "Dark altar with candles, skulls, and runes",
    props: {
      position: [0, 0, 0],
      width: 3,
      height: 2,
      depth: 2,
      color: "#8B7355",
      hasCandles: true,
      candleCount: 4,
      hasSkulls: true,
      skullCount: 2,
      hasRunes: true,
      runeCount: 6,
      hasChains: true,
      chainCount: 4,
      hasBlood: true,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 2,
        max: 6,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 1,
        max: 4,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 2,
        max: 6,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasCandles",
        label: "Has Candles",
        type: "checkbox",
      },
      {
        key: "candleCount",
        label: "Candle Count",
        type: "number",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "hasSkulls",
        label: "Has Skulls",
        type: "checkbox",
      },
      {
        key: "skullCount",
        label: "Skull Count",
        type: "number",
        min: 1,
        max: 6,
        step: 1,
      },
      {
        key: "hasRunes",
        label: "Has Runes",
        type: "checkbox",
      },
      {
        key: "runeCount",
        label: "Rune Count",
        type: "number",
        min: 2,
        max: 12,
        step: 1,
      },
      {
        key: "hasChains",
        label: "Has Chains",
        type: "checkbox",
      },
      {
        key: "chainCount",
        label: "Chain Count",
        type: "number",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "hasBlood",
        label: "Has Blood",
        type: "checkbox",
      },
    ],
  },
  {
    type: "dungeon-throne",
    component: DungeonThrone,
    title: "Dungeon Throne",
    emoji: "👑",
    description: "Dark throne with skulls, chains, and spikes",
    props: {
      position: [0, 0, 0],
      width: 2,
      height: 3,
      depth: 2,
      color: "#8B7355",
      hasArmrests: true,
      hasBackrest: true,
      hasSkulls: true,
      skullCount: 4,
      hasChains: true,
      chainCount: 2,
      hasCushion: true,
      hasSpikes: true,
      spikeCount: 6,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 1.5,
        max: 4,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 2,
        max: 6,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 1.5,
        max: 4,
        step: 0.5,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasArmrests",
        label: "Has Armrests",
        type: "checkbox",
      },
      {
        key: "hasBackrest",
        label: "Has Backrest",
        type: "checkbox",
      },
      {
        key: "hasSkulls",
        label: "Has Skulls",
        type: "checkbox",
      },
      {
        key: "skullCount",
        label: "Skull Count",
        type: "number",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "hasChains",
        label: "Has Chains",
        type: "checkbox",
      },
      {
        key: "chainCount",
        label: "Chain Count",
        type: "number",
        min: 1,
        max: 4,
        step: 1,
      },
      {
        key: "hasCushion",
        label: "Has Cushion",
        type: "checkbox",
      },
      {
        key: "hasSpikes",
        label: "Has Spikes",
        type: "checkbox",
      },
      {
        key: "spikeCount",
        label: "Spike Count",
        type: "number",
        min: 2,
        max: 12,
        step: 1,
      },
    ],
  },
  {
    type: "dungeon-gate",
    component: DungeonGate,
    title: "Dungeon Gate",
    emoji: "🚪",
    description: "Imposing gate with portcullis, skulls, and runes",
    props: {
      position: [0, 0, 0],
      width: 4,
      height: 6,
      depth: 1,
      color: "#8B7355",
      hasPortcullis: true,
      hasChains: true,
      chainCount: 4,
      hasSkulls: true,
      skullCount: 6,
      hasRunes: true,
      runeCount: 8,
      hasSpikes: true,
      spikeCount: 8,
      hasTorches: true,
      torchCount: 2,
    },
    category: "element",
    editableProps: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 3,
        max: 8,
        step: 0.5,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 4,
        max: 12,
        step: 0.5,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        min: 0.5,
        max: 2,
        step: 0.1,
      },
      {
        key: "color",
        label: "Color",
        type: "color",
      },
      {
        key: "hasPortcullis",
        label: "Has Portcullis",
        type: "checkbox",
      },
      {
        key: "hasChains",
        label: "Has Chains",
        type: "checkbox",
      },
      {
        key: "chainCount",
        label: "Chain Count",
        type: "number",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "hasSkulls",
        label: "Has Skulls",
        type: "checkbox",
      },
      {
        key: "skullCount",
        label: "Skull Count",
        type: "number",
        min: 2,
        max: 12,
        step: 1,
      },
      {
        key: "hasRunes",
        label: "Has Runes",
        type: "checkbox",
      },
      {
        key: "runeCount",
        label: "Rune Count",
        type: "number",
        min: 4,
        max: 16,
        step: 1,
      },
      {
        key: "hasSpikes",
        label: "Has Spikes",
        type: "checkbox",
      },
      {
        key: "spikeCount",
        label: "Spike Count",
        type: "number",
        min: 4,
        max: 16,
        step: 1,
      },
      {
        key: "hasTorches",
        label: "Has Torches",
        type: "checkbox",
      },
      {
        key: "torchCount",
        label: "Torch Count",
        type: "number",
        min: 2,
        max: 6,
        step: 1,
      },
    ],
  },
];

export { ELEMENT_CONFIGS };