// True Rooms - Complete rooms with walls/shells
export { default as StartRoom } from './StartRoom';
export { default as CorridorRoom } from './CorridorRoom';
export { default as ColosseumRoom } from './ColosseumRoom';
export { default as StairsRoom } from './StairsRoom';
export { default as MiddleStairsRoom } from './MiddleStairsRoom';

// Biomes - Environmental segments/areas placed inside rooms
export { default as EndBiome } from './EndBiome';
export { default as CoffeeBiome } from './CoffeeBiome';
export { default as MeditationBiome } from './MeditationBiome';
export { default as LibraryBiome } from './LibraryBiome';
export { default as LibraryUpgradeBiome } from './LibraryUpgradeBiome';
export { default as GymBiome } from './GymBiome';
export { default as ShopBiome } from './ShopBiome';
export { default as TreasureBiome } from './TreasureBiome';
export { default as PuzzleBiome } from './PuzzleBiome';
export { default as BossBiome } from './BossBiome';
export { default as ChallengeBiome } from './ChallengeBiome';
export { default as ArenaBiome } from './ArenaBiome';
export { default as PortalBiome } from './PortalBiome';
export { default as CryptBiome } from './CryptBiome';
export { default as TrapBiome } from './TrapBiome';
export { default as SpecialBiome } from './SpecialBiome';
export { default as ShapedShell } from './ShapedShell';
export { default as CustomRoomExample } from './CustomRoomExample';
export { default as RoomFactory } from './RoomFactory';
